# VELOCITY TEMPLATES (VelocityAutoConfiguration)spring:
velocity:
  charset: UTF-8
  resourceLoaderPath: classpath:/templates/

spring:
  devtools:
    restart:
      exclude: templates/**,static/**,public/**

# 日志相关
logging:
#  config: classpath:logback-spring.xml
  path: ~/logs